[project]
name = "task-manager"
version = "0.1.0"
description = "Simple CLI Task Manager"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "argon2-cffi>=23.1.0",
    "colorama>=0.4.6",
    "cryptography>=44.0.2",
    "pyfiglet>=1.0.2",
]
